# Generated by Django 6.0.4 on 2026-05-02 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('provinces', '0001_initial'),
        ('waste_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_projects', to='waste_sites.wastesite'),
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='provinces.province'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sites', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='waste_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='waste_sites.wastesite'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsite',
            unique_together={('project', 'waste_site')},
        ),
    ]
