# Generated by Django 6.0.4 on 2026-05-02 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteSiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'waste_sites_wastesitetype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('operational_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('planned', 'Planned'), ('closed', 'Closed')], default='active', max_length=16)),
                ('capacity_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waste_sites', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_sites', to='provinces.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_sites', to='provinces.province')),
                ('site_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='waste_sites.wastesitetype')),
            ],
            options={
                'db_table': 'waste_sites_wastesite',
                'ordering': ['name'],
            },
        ),
    ]
