# Generated by Django 6.0.4 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GisLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('layer_type', models.CharField(choices=[('wms', 'WMS'), ('wfs', 'WFS'), ('vector_tiles', 'Vector tiles'), ('geojson', 'GeoJSON'), ('internal', 'Internal')], default='internal', max_length=32)),
                ('url', models.URLField(blank=True)),
                ('style_json', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gis_gislayer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapViewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zoom_level', models.PositiveSmallIntegerField(default=10)),
                ('visible_layer_slugs', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gis_mapviewstate',
                'ordering': ['-updated_at'],
            },
        ),
    ]
