# Generated by Django 6.0.4 on 2026-05-02 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0001_initial'),
        ('waste_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gislayer',
            name='waste_site',
            field=models.ForeignKey(blank=True, help_text='Optional: layer scoped to one site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gis_layers', to='waste_sites.wastesite'),
        ),
        migrations.AddField(
            model_name='mapviewstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_view_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
