# Generated by Django 6.0.4 on 2026-05-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('evidence', 'Evidence'), ('site_photo', 'Site photo'), ('report_output', 'Report output'), ('general', 'General')], default='general', max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'uploads_fileattachment',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
